package uk.ac.rgu.rgtodu.data;

import android.content.Context;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Random;

/**
 * This class provides the single point of truth in the app for {@link TaskRepository}s, and
 * will in the future deal with downloading, storing, and retrieving them.
 * @author  David Corsar
 */
public class TaskRepository {

    // member field for database operations
    private TaskDao taskDao;

    /**
     * A field for how dates should be formatted before displaying to users
     * with the day of the month as a number, and the month as text
     */
    private static final String DATE_FORMAT = "dd MMM";

    /**
     * The Singleton instance for this repository
     */
    private static TaskRepository INSTANCE;

    /**
     * The Context that the app is operating within
     */
    private Context context;

    /**
     * Gets the singleton {@link TaskRepository} for use when managing {@link Task}s
     * in the app.
     * @return The {@link TaskRepository} to be used for managing {@link Task}s in the app.
     */
    public static TaskRepository getRepository(Context context){
        if (INSTANCE == null){
            synchronized (TaskRepository.class) {
                if (INSTANCE == null)
                    INSTANCE = new TaskRepository();
                // for accessing the database
                INSTANCE.taskDao = TaskDatabase.getDatabase(context).taskDao();
                // store the context in case its required
                INSTANCE.context = context;
            }
        }
        return INSTANCE;
    }

    public void storeTask(Task task){
        taskDao.insert(task);
    }

    public void storeTasks(List<Task> tasks){
        taskDao.insertTasks(tasks);
    }

    public void deleteTask(Task task){
        taskDao.delete(task);
    }

    public List<Task> getAllTasks(){
        return taskDao.getAllTasks();
    }

    /**
     * Returns a list containing the specified number of Tasks generated by getTask
     * @param number The number of Tasks to return
     * @return
     */
    public List<Task> getSyntheticTasks(int number){
        List<Task> tasks = new ArrayList<>(number);
        for (int i = 0; i < number; i++){
            Task t = getSyntheticTask();
         
            tasks.add(t);
        }
        return tasks;
    }

    /**
     * Returns a {@link Task} with randomly generated info.
     * @return a {@link Task} for tomorrow, with randomly generated details.
     */
    public Task getSyntheticTask(){
        // create a new Task
        Task t = new Task();

        // A random number generator for populating the fields
        Random random = new Random();

        int id = random.nextInt(10000);
        // set the name randomly
        t.setName(String.format("Task %s", id));

        // set the description to some placeholder
        t.setDescription("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.");

        // set estimated hours to completely to be random between 1 and 5
        t.setHoursToCompletion(random.nextInt(5));

        // set the priority randomly
        t.setPriority(TaskPriority.values()[random.nextInt(3)]);

        // schedule it for up to 14 days in the future
        long offset = 1000*60*60*24 * random.nextInt(14);
        t.setDeadline(new Date(System.currentTimeMillis() + offset));

        return t;
    }


}
